development:
  adapter: postgresql
  encoding: unicode
  database: exquisiter_corpse_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: exquisiter_corpse_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: exquisiter_corpse_production
  pool: 5